swagger: '2.0'
info:
  version: '1.0'
  title: "apicoltori-se2-project"
  description: Project for the Software Engineering 2 course held at the bachelor's degree in Computer Science at the University of Trento.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: apicoltori-se2-project.herokuapp.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json